global:
  scrape_interval: 10s
  evaluation_interval: 10s

# Indique à Prometheus où trouver les fichiers de règles d'alerte
rule_files:
  - "rules/*.yml" # Charge tous les fichiers .yml dans le sous-répertoire 'rules'

#plusieurs configs possible
scrape_configs:
    
  - job_name: 'prometheus' # Nom du job pour Prometheus lui-même
    static_configs:
      - targets: ['localhost:9090'] # Prometheus se monitorera lui-même
    metrics_path: /prometheus/metrics

  - job_name: 'node-exporter' # Nom du job pour node-exporter
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'bike_api'
    static_configs:
      - targets: ['bike-api:8080']
    
