{
 "title": "Bike Api Performance",
 "description": "Performance API ",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Taux de Requêtes",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " (sum by (endpoint) (rate(bike_requests_total[30m])))",
     "legendFormat": "__auto"
    },
    { "expr": "rate(bike_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "la latence (P95)",
   "type": "timeseries",
   "description": "la latence (P95)",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bike_request_duration_seconds_bucket[5m])) by (endpoint, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taux d'erreur",
   "type": "timeseries",
   "description": "Assez difficile de faire des erreurs dans un prédict de régression et la malformation d'URL est capté par pydantic et ne permet pas de rentrer dans l'endpoint simplement. Donc à date je n'ai que des codes 200.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(endpoint, status_code) (bike_requests_total{status_code!=\"200\"})",
     "legendFormat": "__auto"
    },
    { "expr": "bike_request_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}