{
 "title": "Bike System Dashboard",
 "description": "testing one example",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) *100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/ File system usage",
   "type": "gauge",
   "description": "File system availability df -Ph /",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "alertes à Malibu", "type": "alertlist", "description": "ma liste alerte d'alertes", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "CPU x MEM avail",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) *100))",
     "legendFormat": "CPU Used"
    },
    {
     "expr": "100 - (avg by (instance) (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "MEM Avail"
    }
   ]
  }
 ]
}