{
 "title": "Bike Model Performance & Drift",
 "time": { "from": "2026-06-07T18:48:38.321Z", "to": "2026-06-07T19:14:53.135Z" },
 "panels": [
  {
   "title": "bike_model_rmse",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bike_model_rmse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "bike_model_mae",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bike_model_mae_mean", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "bike_model_r2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bike_model_r2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "bike_model_drift",
   "type": "gauge",
   "description": "pourcentage de column en drift",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bike_model_drift_share", "legendFormat": "__auto" }
   ]
  }
 ]
}